[tool.poetry]
name = "packages"
version = "0.1.0"
description = "This consists of the packages used by the SFC Emulator."
authors = ["Theviyanthan K."]
license = "Apache-2.0 license"
packages = [
    { include = "shared" }
]

[tool.poetry.dependencies]
python = "^3.8"
PyYAML = "^6.0.1"
docker = "6.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
