[tool.poetry]
name = "sfc-emulator"
version = "0.1.0"
description = "This is an emulator built on top of Containernet to benchmark and evaluate solutions to the NFV-RA problem."
authors = ["Theviyanthan K."]
license = "Apache-2.0 license"
packages = [
    { include = "shared" },
    { include = "models", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.8"
pyyaml = "^6.0.1"
jinja2 = "^3.1.2"
docker = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
