apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    url: http://influxdb:8086
    isDefault: true
    secureJsonData:
      token: K6_INFLUXDB_GRAFANA
    jsonData:
      version: Flux
      organization: SFC_Test
      defaultBucket: SFC_Test
